### PR TITLE
Corrections and additions to powerfit tutorial

### PR DESCRIPTION
**Pull request by latrocinia**
Please check whether all the points raised were added properly. If not let me know.

### CODE REVIEW

**Comment by amjjbonvin** [comment]
Nice work!

**Comment by latrocinia** [comment]
I notice that their still remain some small errors. I'll send another last fix soon, to properly address those.


________________________________

**Comment by amjjbonvin** [comment]
Do update first - I had a new commit

> On 07 Mar 2016, at 16:15, Gydo van Zundert <notifications@github.com> wrote:
> 
> I notice that their still remain some small errors. I'll send another last fix soon, to properly address those.
> 
> 
> ________________________________
> From: Alexandre Bonvin [notifications@github.com]
> Sent: Monday, March 07, 2016 3:15 PM
> To: haddocking/haddocking.github.io
> Cc: Zundert, G.C.P. van (Gydo)
> Subject: Re: [haddocking.github.io] Corrections and additions to powerfit tutorial (#40)
> 
> 
> Nice work!
> 
> —
> Reply to this email directly or view it on GitHub<https://github.com/haddocking/haddocking.github.io/pull/40#issuecomment-193264165>.
> —
> Reply to this email directly or view it on GitHub.
> 

==================================
Alexandre Bonvin
Talingweide 91, 3403 AC IJsseltstein, NL
Tel: +31-30-7525883
Email: alexandre.bonvin@gmail.com
==================================

**Comment by latrocinia** [comment]
Will do!

________________________________

**Pull request merged**
