### PR TITLE
Added PowerFit tutorial

### PR DESCRIPTION
**Pull request by latrocinia**

### CODE REVIEW

**Comment by JoaoRodrigues** [comment]
Do not merge. 

There are a few typos in the text, I'll email you about them. Also, I think it would make sense to use the coloring scheme we use in the molmod course for linux & pymol commands, instructions, questions, etc, to be consistent. Do you agree?

**Comment by amjjbonvin** [comment]
Sure - but we need it done very soon - planned for Taiwan over one week 

=================================
 Prof. A.M.J.J. Bonvin | Faculty of Science
 Utrecht University | bonvinlab.org 
 a.m.j.j.bonvin@uu.nl | T: +31 30 2533859 
=================================

**Comment by JoaoRodrigues** [comment]
On it. 

@latrocinia Why do you use `-a 20` if the default is 10? Would this impact the results of the search on this particular case?

**Comment by amjjbonvin** [comment]
Should run in a reasonable time for the tutorial...

===============================
 Prof. A.M.J.J. Bonvin | Faculty of Science
 Utrecht University | bonvinlab.org 
 a.m.j.j.bonvin@uu.nl | T: +31 30 2533859 
=================================

**Comment by JoaoRodrigues** [comment]
OK, so I got it wrong from the text. I thought 20 was slower than 10!

A sáb, 5/03/2016, 12:51, Alexandre Bonvin <notifications@github.com>
escreveu:

**Comment by amjjbonvin** [comment]
Hi Gydo

I leave it to you to deal with Joao’s changes first.

Had a quick look at the files in GitHub. Did you add the structure validation / clash analysis part?
Did you get my email with the simple script to calculate distance histograms for the contacts up to 5A?

Cheers
Alexandre

> On 05 Mar 2016, at 18:06, Gydo van Zundert <notifications@github.com> wrote:
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/haddocking/haddocking.github.io/pull/37
> 
> Commit Summary
> 
> 	• Added PowerFit tutorial
> File Changes
> 
> 	• M education/index.md (8)
> 	• A education/powerfit-tutorial/index.md (202)
> Patch Links:
> 
> 	• https://github.com/haddocking/haddocking.github.io/pull/37.patch
> 	• https://github.com/haddocking/haddocking.github.io/pull/37.diff
> —
> Reply to this email directly or view it on GitHub.
> 

---------------------------------------------------------------------------------------------------------------------------
 Dr. Alexandre M.J.J Bonvin              | Professor of Computational Structural Biology 
 Faculty of Science, Utrecht University, Padualaan 8, 3584 CH Utrecht, the Netherlands
 Phone: +31-30-2533859 / 2652      |   Fax: +31-30-2537623
 Email: a.m.j.j.bonvin@uu.nl
 http://www.uu.nl/staff/AMJJBonvin  |  http://www.bonvinlab.org 
---------------------------------------------------------------------------------------------------------------------------

**Comment by latrocinia** [comment]
Indeed, the 20 degree interval results in fewer rotations -> Faster
________________________________________

**Comment by latrocinia** [comment]
Hey Alex,

No I didn't actually. I'll add the part, for clashing analysis. Wait for the revision.

Cheers,
Gydo

________________________________________

**Comment by latrocinia** [comment]
I see that the csh script requires the contact program in addition to xmgrace. Those programs should be made available in the VM. 

There were some bugs in the csh-script, the numbers of the bins are incorrect. I'll upload an updated version in the powerfit-tutorial repo.

________________________________________

**Comment by amjjbonvin** [comment]
Ok - xmgrace should be already there (I hope).
the contacts-chainID program should be added (taken from HADDOCK tools

As for the script you could probably write a much better one in Python… But it does the job

> On 06 Mar 2016, at 17:18, Gydo van Zundert <notifications@github.com> wrote:
> 
> I see that the csh script requires the contact program in addition to xmgrace. Those programs should be made available in the VM. 
> 
> There were some bugs in the csh-script, the numbers of the bins are incorrect. I'll upload an updated version in the powerfit-tutorial repo.
> 
> ________________________________________
> From: Alexandre Bonvin [notifications@github.com]
> Sent: Sunday, March 06, 2016 4:22 PM
> To: haddocking/haddocking.github.io
> Cc: Zundert, G.C.P. van (Gydo)
> Subject: Re: [haddocking.github.io] Added PowerFit tutorial (#37)
> 
> Hi Gydo
> 
> I leave it to you to deal with Joao�s changes first.
> 
> Had a quick look at the files in GitHub. Did you add the structure validation / clash analysis part?
> Did you get my email with the simple script to calculate distance histograms for the contacts up to 5A?
> 
> Cheers
> Alexandre
> 
> > On 05 Mar 2016, at 18:06, Gydo van Zundert <notifications@github.com> wrote:
> >
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/haddocking/haddocking.github.io/pull/37
> >
> > Commit Summary
> >
> > � Added PowerFit tutorial
> > File Changes
> >
> > � M education/index.md (8)
> > � A education/powerfit-tutorial/index.md (202)
> > Patch Links:
> >
> > � https://github.com/haddocking/haddocking.github.io/pull/37.patch
> > � https://github.com/haddocking/haddocking.github.io/pull/37.diff
> > �
> > Reply to this email directly or view it on GitHub.
> >
> 
> ---------------------------------------------------------------------------------------------------------------------------
> Dr. Alexandre M.J.J Bonvin | Professor of Computational Structural Biology
> Faculty of Science, Utrecht University, Padualaan 8, 3584 CH Utrecht, the Netherlands
> Phone: +31-30-2533859 / 2652 | Fax: +31-30-2537623
> Email: a.m.j.j.bonvin@uu.nl
> http://www.uu.nl/staff/AMJJBonvin | http://www.bonvinlab.org
> ---------------------------------------------------------------------------------------------------------------------------
> 
> 
> 
> �
> Reply to this email directly or view it on GitHub<https://github.com/haddocking/haddocking.github.io/pull/37#issuecomment-192913679>.
> —
> Reply to this email directly or view it on GitHub.
> 

==================================
Alexandre Bonvin
Talingweide 91, 3403 AC IJsseltstein, NL
Tel: +31-30-7525883
Email: alexandre.bonvin@gmail.com
==================================

**Comment by latrocinia** [comment]
Great!! The script is fine, just some numbers were wrong :-)). 


________________________________________

**Comment by JoaoRodrigues** [comment]
Sounds good! I'll close this PR then. @latrocinia make a new one with everything whenever you are ready. Indeed that script should be re-written to make things easier :) And matplotlib should be installed on the machine too!

**Comment by amjjbonvin** [comment]
No sure which script you are referring to, but doesn't the VM already have xmgrace? We should avoid installing too much stuff :-)

=================================
 Prof. A.M.J.J. Bonvin | Faculty of Science
 Utrecht University | bonvinlab.org 
 a.m.j.j.bonvin@uu.nl | T: +31 30 2533859 
=================================

**Pull request closed without merging**
