### PR TITLE
Move Gydo to alumni ...

### PR DESCRIPTION
**Pull request by latrocinia**

### CODE REVIEW

**Comment by amjjbonvin** [comment]
Was already making more changes. Will take those over.
What about your Stanford affiliation?

**Comment by latrocinia** [comment]
True, it is actually a joined position with Schrodinger, Stanford and UCSF.
Still, I think this should do it, my contract after all is with them …

**Comment by amjjbonvin** [comment]
Ok - whatever you prefer, but showing Standord and UCSG might be good :-)

**Comment by latrocinia** [comment]
I guess youre right :-). The details of Stanford can be copied from Joao,
and for UCSF

UCSF, San Francisco, CA.

:-)

**Pull request closed without merging**
