### PR TITLE
Updating Jekyll3 and gh-pages configurations. Improvements to tutorial

### PR DESCRIPTION
**Pull request by JoaoRodrigues**
Instead of #30.

I destroyed my own commit history in favor of the one in the main repository. This will nevertheless require a reset --hard on the main repository to revert the last commit, but the changes are minor. I can handle this.

### CODE REVIEW

**Comment by amjjbonvin** [comment]
João - Do you handle it or should I accept the pull?
Thanks for all the good work!

=================================
 Prof. A.M.J.J. Bonvin | Faculty of Science
 Utrecht University | bonvinlab.org 
 a.m.j.j.bonvin@uu.nl | T: +31 30 2533859 
=================================

**Comment by JoaoRodrigues** [comment]
I'll handle it big boss. And write down instructions on how to update your
repo afterwards. Credit to Jörg! We still have to go over the docking part.

A dom, 21/02/2016, 23:21, Alexandre Bonvin <notifications@github.com>
escreveu:

**Comment by amjjbonvin** [comment]
Top!

And the docking part needs to have the three default conformations added to it - now we are not getting good results…

> On 22 Feb 2016, at 08:37, João Rodrigues <notifications@github.com> wrote:
> 
> I'll handle it big boss. And write down instructions on how to update your
> repo afterwards. Credit to Jörg! We still have to go over the docking part.
> 
> A dom, 21/02/2016, 23:21, Alexandre Bonvin <notifications@github.com>
> escreveu:
> 
> >
> > João - Do you handle it or should I accept the pull?
> > Thanks for all the good work!
> >
> > =================================
> > Prof. A.M.J.J. Bonvin | Faculty of Science
> > Utrecht University | bonvinlab.org
> > a.m.j.j.bonvin@uu.nl | T: +31 30 2533859
> > =================================
> >
> >
> > > On 22 Feb 2016, at 05:42, João Rodrigues <notifications@github.com>
> > wrote:
> > >
> > > Instead of #30.
> > >
> > > I destroyed my own commit history in favor of the one in the main
> > repository. This will nevertheless require a reset --hard on the main
> > repository to revert the last commit, but the changes are minor. I can
> > handle this.
> > >
> > > You can view, comment on, or merge this pull request online at:
> > >
> > > https://github.com/haddocking/haddocking.github.io/pull/31
> > >
> > > Commit Summary
> > >
> > > Updated Joao information
> > > Corrections suggested by schaarj
> > > Improve reproducibility of local setup(s) relative to github pages
> > deployment.
> > > Updated instructions to improve reproducibility
> > > Changes suggested by @schaarj and some more:
> > > Fixed links to support Jekyll3 change in gh-pages
> > > Changes suggested by @schaarj and some more:
> > > File Changes
> > >
> > > M Gemfile (3)
> > > M README.md (43)
> > > M _config.yml (27)
> > > M _data/alumni.yml (4)
> > > M education/molmod/index.md (6)
> > > M education/molmod/modelling.md (127)
> > > M education/molmod/simulation.md (415)
> > > M software/index.md (2)
> > > Patch Links:
> > >
> > > https://github.com/haddocking/haddocking.github.io/pull/31.patch
> > > https://github.com/haddocking/haddocking.github.io/pull/31.diff
> > > —
> > > Reply to this email directly or view it on GitHub.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/haddocking/haddocking.github.io/pull/31#issuecomment-187050194>
> > .
> >
> —
> Reply to this email directly or view it on GitHub.
> 

==================================
Alexandre Bonvin
Talingweide 91, 3403 AC IJsseltstein, NL
Tel: +31-30-7525883
Email: alexandre.bonvin@gmail.com
==================================

**Comment by JoaoRodrigues** [comment]
Solved. To update your branches you should:
```bash
git reset --hard 55a590088a7d2ccdb88afa795ae7f952795ff6ef
git pull haddocking master # or whatever remote name you gave this repository
```

This is evil by all git standards. We should really try and never do this again!

**Pull request closed without merging**
